#+TITLE: Basics of Biological Chemistry (Fall 2014)
#+AUTHOR: Cedric Lood
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt, a4paper,titlepage]
#+LATEX_HEADER: \usepackage[left=2.35cm, right=3.35cm, top=3.35cm, bottom=3.35cm]{geometry}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage{chemfig}
#+TITLE:
#+BEGIN_LaTeX
\setlength{\parskip}{0pt}%
\setlength{\parindent}{0pt}%
\renewcommand{\thesubsubsection}{\alph{subsubsection}.)}
\include{title}
\setcounter{tocdepth}{3}
\tableofcontents
\clearpage
#+END_LaTeX
#+STARTUP: latexpreview
#+OPTIONS: LaTeX:dvipng, toc:nil



* Prof. J. Vanderleyden – dr. H. Steenackers
** Chemical reaction equation

Consider the following reaction: (NH_{4})_{2}CO_{3} +  Zn(NO_{3})_{2} →  NH_{4}NO_{3} + ZnCO_{3}

*** Balance the equation  
(NH_{4})_{2}CO_{3} +  Zn(NO_{3})_{2} →  2 NH_{4}NO_{3} + ZnCO_{3}

*** Reactants and products
=Q:= Name all reactants and reaction products.

=A:=
- (NH_{4})_{2}CO_{3} : Ammonium carbonate
- Zn(NO_{3})_{2} : Zinc nitrate
- NH_{4}NO_{3} : Ammonium nitrate
- ZnCO_{3} : Zinc carbonate

*** Lewis structure, VESPR
=Q:= Construct the Lewis structures of the polyatomic ions you recognize
and predict their molecular structure using the VSEPR theory.

=A:=
- Lewis Structure of the ions: 
#+BEGIN_LaTeX
\renewcommand{\arraystretch}{1.5}
\begin{tabular}{ c | c | c | c}
Ammonium & Carbonate & Zinc & Nitrate  \\
\hline
\chemfig{N^{+}(-[:0]H)(-[:90]H)(-[:180]H)(-[:270]H)} &
\chemfig{\lewis{3:5:,O}=C(-[1]\lewis{3:1:7:,O}^{-})(-[7]\lewis{1:7:5:,O}^{-})} &
\chemfig{\lewis{4:,Zn^{2+}}} &
\chemfig{\lewis{3:5:,O}=N^{+}(-[1]\lewis{3:1:7:,O}^{-})(-[7]\lewis{1:7:5:,O}^{-})}\\
\end{tabular}
#+END_LaTeX

- Molecular structure prediction:
#+BEGIN_LaTeX
\renewcommand{\arraystretch}{1.5}
\begin{tabular}{ c | c | c | c}
Ammonium & Carbonate & Zinc & Nitrate  \\
\hline
\chemfig{N^{+}(-[2]H)(-[5]H)(<[6]H)(<:[7]H)} &
\chemfig{O=C(-[1]O^{-})(-[7]O^{-})} &
\chemfig{Zn^{2+}} &
\chemfig{O=N^{+}(-[1]O^{-})(-[7]O^{-})}\\
\end{tabular}
#+END_LaTeX

*** Oxidation states
=Q:= Determine the oxidation state of all the atoms in all the
compounds. Is this an oxidation-reduction reaction?

=A:= Ammonium Carbonate and Zinc Nitrate (the reactants) are very soluble
in water and will thus move freely. The Zinc and Carbonate ions will
then precipitate.

- Zn has an oxidation state of 2:  Zn →  Zn^{2+} + 2 e^{-}
- (CO_{3}) has an oxidation state of 4: (CO_{3})^{2-} + 2 e^{-} → CO_{3}


*** Mass
=Q:= How many grams of ZnCO3 can be prepared from 400g Zn(NO3)2 by
using sufficient(NH4)2CO3?

=A:= Let's start by computing the molecular weight of the 2 reactants:

- Molecular weigth of Zn(NO_{3})_{2} :: 189.36 g/mol
- Molecular weigth of (NH_{4})_{2}CO_{3} :: 96.09 g/mol

Given that there are 400g of Zn(NO_{3})_{2}, we can calculate the
number of moles of reactant (and ignore that of (NH_{4})_{2}CO_{3}
since it is in excess):

- Moles of Zn(NO_{3})_{2} :: 400 g / 189.36 g/mol = 2.11237 moles

From this last figure, we can infer that the number of moles of
ZnCO_{3} will be 2.11237. Given the molecular mass of ZnCO_{3}, we can
compute the amount of ZnCO_{3} produced to be: 2.11237 mol * 125.3889
g/mol = 264.8678 g.

** DNA sequence analysis

The following diagram shows part of a template DNA strand, with
sections X,Y and Z being the exons of a gene:

#+BEGIN_EXAMPLE
5'                        3'
GTA GGT TGT ATC GAT GGT CAT
---     -------         ---
 X         Y             Z
#+END_EXAMPLE

*** DNA Replication
=Q:= What is the corresponding sequence on the new daughter strand
made from the given parent strand during replication?

=A:= Given the principle of base pairing, we can determine the daughter
sequence to be (here in the 3' to 5' direction):

#+BEGIN_EXAMPLE
5'                        3'
GTA GGT TGT ATC GAT GGT CAT
CAT CCA ACA TAG CTA CCA GTA
3'                        5'
#+END_EXAMPLE

*** Translated Protein
=Q:= What polypeptide sequence will be synthesized from the given template
DNA? Give a short overview of the different processes (and enzymes)
involved in the synthesis of polypeptides from template DNA. Where in
the cell do these processes take place?

=A:= The synthesized polypeptide will consist of the amino acids =VCIH=. 

*** Mutated exon
=Q:= What polypeptide sequence will be synthesized if the ATC in exon
Y is mutated to TTC? What polypeptide sequence will be synthesized if
the ATC in exon Y is mutated to ATG? Which of those substitution
mutations is likely to be more harmful? Why?

=A:=
*** Interactions with antibiotics
=Q:= Which steps in polypeptide synthesis are affected by resp. the
macrolide antibiotics and the tetracycline antibiotics?

=A:=
*** Comparison of error rates
=Q:= The error rate in RNA synthesis is much higher than the error rate
of DNA replication. What is the origin of this difference? Motivate
why this is not a serious problem.

=A:=
** tRNA 3D-Structure
=Q:= All tRNA molecules have a particular 3D-structure. Which
functional groups and which chemical bonds/interactions contribute to
this particular structure? Why is this particular structure of
importance for the biological function?

=A:=
* Prof. B. Sels
** Biopolymer organisation
=Q:= The course and the textbook systematically organize four important
biopolymers mainly according to their chemical structure. Attempt a
complete reorganization of the various biopolymer structures (and
subfamilies!) according to the following three physiological
functions: energy, structure, and communication. Explain the
physiological function of each biopolymer type with regard to its
chemical structure and/or physical properties.

=A:=
** Chemical structure of proteins and proteins separation
=Q:= Draw the chemical structure of the following two oligopeptide
structures, a) Gln-Ser-Lys-Lys-Ser and b) Cys-Asp-Asp-Glu-Lys,
determine its net charge in physiological conditions. How would you
separate the two peptides ?  

=A:=
** Chemical structure of disaccharides
=Q:= Draw the chemical structure of the following disaccharides: a)
the \beta-anomer of \alpha(1→6)galactoglucose and b)
\beta,\alpha(1→2)glucofructose.

=A:=
* Prof. D. De Vos
Considering the following molecule:

#+ATTR_LATEX: width=7cm
[[./Figures/Part3MoleculeRaw.pdf]]

** Functional groups
=Q:= Name all functional groups

=A:=

** Water and oil solubility factors
=Q:= Indicate which groups make the molecule rather water-soluble
than oil-soluble

=A:=
